In [1]:
using Knet, Images, Colors

In [2]:
wdict = Knet.load("dictionary.jld2", "dict")
UNK = wdict["<unk>"]
w2i(x) = get(wdict, x, UNK)

w2i (generic function with 1 method)

In [3]:
dataset4 = Knet.load("4dataset_total.jld2", "dataset")
summary(dataset4)

"11532-element Array{Tuple{NTuple{4,Array{Normed{UInt8,8},3}},String},1}"

In [4]:
summary(images4)

UndefVarError: UndefVarError: images4 not defined

In [3]:
images4 = []
images2 = []
images1 = []
labels = []

0-element Array{Any,1}

In [4]:
sentence1 = w2i.(split("Climb down the ladder Climb down the ladder"))
    sentence2 = w2i.(split("Climb down the ladder Climb down the ladder"))
    sentence3 = w2i.(split("Go to the right side of the room"))
    sentence4 = w2i.(split("Jump to the rope Jump to the rope"))
    sentence5 = w2i.(split("Climb down the ladder Climb down the ladder"))
    sentence6 = w2i.(split("Climb down the ladder Climb down the ladder"))
    sentence6 = w2i.(split("Go to the center of the room center"))
    sentence7 = w2i.(split("Go to the center of the room center"))
    sentence8 = w2i.(split("Go to the center of the room center"))
    sentence9 = w2i.(split("Go to the left side of the room "))
    sentence10 = w2i.(split("Go to the left side of the room "))
    
    
    

    sentence11 = w2i.(split("Climb up the ladder Climb up the ladder"))
    sentence12 = w2i.(split("Climb up the ladder Climb up the ladder"))
    sentence13 = w2i.(split("Get the key Get the key Get key"))
    sentence14 = w2i.(split("Climb down the ladder Climb down the ladder"))
    sentence15 = w2i.(split("Climb down the ladder Climb down the ladder"))
    sentence16 = w2i.(split("Go to the center of the room center"))
    sentence17 = w2i.(split("Go to the center of the room center"))
    sentence18 = w2i.(split("Go to the right side of the room"))
    sentence19 = w2i.(split("Go to the right side of the room"))
    sentence20 = w2i.(split("Climb up the ladder Climb up the ladder"))
    sentence21 = w2i.(split("Climb up the ladder Climb up the ladder"))
    sentence22 = w2i.(split("Jump to the rope Jump to the rope"))
    sentence23 = w2i.(split("Jump to the rope Jump to the rope"))
    sentence24 = w2i.(split("Go to the left side of the room"))
    sentence25 = w2i.(split("Go to the left side of the room"))
    
    
    dont_do_sentence = w2i.(split("Jump in place Jump in place Jump place"))
    dont_do_sentence2 = w2i.(split("Fall down Fall down Fall down Fall down"))
    
    sentences = []
    push!(sentences, sentence1, sentence2, sentence3, sentence4, sentence5, sentence6, sentence7, sentence8, sentence9, sentence10,sentence1, sentence2, sentence3, sentence4, sentence5, sentence6, sentence7, sentence8, sentence9, sentence10, sentence24, sentence25, sentence11, sentence12, sentence13, sentence14, sentence15, sentence16, sentence17, sentence18, sentence19, sentence20, sentence21, sentence22, sentence23)


35-element Array{Any,1}:
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [12, 15, 5, 22, 21, 17, 5, 18]
 [24, 15, 5, 25, 24, 15, 5, 25]
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [12, 15, 5, 19, 17, 5, 18, 19]
 [12, 15, 5, 19, 17, 5, 18, 19]
 [12, 15, 5, 19, 17, 5, 18, 19]
 [12, 15, 5, 20, 21, 17, 5, 18]
 [12, 15, 5, 20, 21, 17, 5, 18]
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [12, 15, 5, 22, 21, 17, 5, 18]
 ⋮                             
 [3, 7, 5, 6, 3, 7, 5, 6]      
 [8, 5, 9, 8, 5, 9, 8, 9]      
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [3, 4, 5, 6, 3, 4, 5, 6]      
 [12, 15, 5, 19, 17, 5, 18, 19]
 [12, 15, 5, 19, 17, 5, 18, 19]
 [12, 15, 5, 22, 21, 17, 5, 18]
 [12, 15, 5, 22, 21, 17, 5, 18]
 [3, 7, 5, 6, 3, 7, 5, 6]      
 [3, 7, 5, 6, 3, 7, 5, 6]      
 [24, 15, 5, 25, 24, 15, 5, 25]
 [24, 15, 5, 25, 24, 15, 5, 25]

In [ ]:
i=1
for data in dataset4
#     data = dataset4[i]
    IJulia.clear_output(true)
    (f1,f2, f3, f4), sent = data
#     f1 = Float32.(Gray.(colorview(RGB, permutedims(f1, (3,1,2)))))
#     f2 = Float32.(Gray.(colorview(RGB, permutedims(f2, (3,1,2)))))
    f3 = Float32.(Gray.(colorview(RGB, permutedims(f3, (3,1,2)))))
    f4 = Float32.(Gray.(colorview(RGB, permutedims(f4, (3,1,2)))))
#     four_frames = cat(f1, f2, f3, f4; dims=3)
    both_frames = cat(f3, f4; dims=3)
#     last_frame = f4
    wordids = w2i.(split(sent))
    push!(labels, wordids)
#     push!(images4,four_frames)
    push!(images2,both_frames)
#     push!(images1,last_frame)
    println(i)
    i+=1
end

2187


In [ ]:
for data in dataset4
    IJulia.clear_output(true)
    (f1,f2,f3,f4) = data
    f3 = Float32.(Gray.(colorview(RGB, permutedims(f3, (3,1,2)))))
    f4 = Float32.(Gray.(colorview(RGB, permutedims(f4, (3,1,2)))))
    both_frames = cat(f3, f4; dims=3)
    last_frame = f4
    push!(images2,both_frames)
    push!(images1,last_frame)    
    
end

In [11]:
image_batch4 = reshape(cat1d(images4...), (210,160,4,length(images4)))
summary(image_batch4)

OutOfMemoryError: OutOfMemoryError()

In [ ]:
image_batch2 = reshape(cat1d(images2...), (210,160,2,length(dataset4)))
summary(image_batch2)

In [7]:
image_batch1 = reshape(cat1d(images1...), (210,160,1,length(dataset4)))
summary(image_batch1)

"210×160×1×9763 Array{Float32,4}"

In [ ]:
summary(labels)

In [ ]:
function seqbatch(sentences)
    batchsize = size(sentences, 1)
    maxlength = findmaxlength(sentences)
    for sent in sentences
        if(length(sent) < maxlength)
            for i = 1:maxlength-length(sent)
                push!(sent, 2)
            end
        end
    end
    reshape(cat1d(sentences...), (maxlength,length(labels)))
end

In [ ]:
function findmaxlength(sentences)
    maxsize = 0
    count = 0
    for sent in sentences
        count = count + 1
        if(length(sent) > maxsize)
            maxsize = length(sent)
        end
    end
    return maxsize
end

In [ ]:
labels = seqbatch(labels)
summary(labels)

In [ ]:
data4 = Tuple{Array{Float32,3},Array{Int32,1}}[]
for i = 1:length(labels[1,:])
    x1 = image_batch4[:,:,:,i]
    x2 = labels[:,i]
    push!(data4, (x1,x2))
end
summary(data4)

In [11]:
data2 = Tuple{Array{Float32,3},Array{Int32,1}}[]
for i = 1:length(dataset4)
    x1 = image_batch2[:,:,:,i]
    x2 = labels[:,i]
    push!(data2, (x1,x2))
    println(i)
end
summary(data2)
    

"9763-element Array{Tuple{Array{Float32,3},Array{Int32,1}},1}"

In [12]:
data1 = Tuple{Array{Float32,3},Array{Int32,1}}[]
for i = 1:length(dataset4)
    x1 = image_batch1[:,:,:,i]
    x2 = labels[:,i]
    push!(data1, (x1,x2))
end
summary(data1)
    

"9763-element Array{Tuple{Array{Float32,3},Array{Int32,1}},1}"

In [ ]:
Knet.save("data4.jld2", "dataset", data4)

In [12]:
Knet.save("data2.jld2", "dataset", data2)

In [13]:
Knet.save("data1.jld2", "dataset", data1)